name: ios

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Шаг 1: Checkout репозиторий без загрузки файлов из LFS
    - name: Checkout code without Git LFS
      uses: actions/checkout@v2
      with:
        lfs: false  # Отключаем Git LFS

    # Шаг 2: Установка Ruby для CocoaPods
    - name: Set up Ruby (for CocoaPods)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'  # Укажи свою версию Ruby

    # Шаг 3: Установка CocoaPods зависимостей
    #- name: Install CocoaPods dependencies
    #  run: |
    #    gem install cocoapods
    #   pod install

    # Шаг 4: Сборка и юнит-тестирование проекта (без снапшот-тестов)
    #- name: Build and Run Unit Tests
    #  run: |
    #    xcodebuild test -workspace Snp-tst.xcworkspace -scheme Snp-tst -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -only-testing:UnitTests -destination-timeout 60 CODE_SIGNING_ALLOWED=NO | xcpretty