name: snapshot_tests

on:
  workflow_dispatch: # manually start via GitHub

jobs:
  snapshot-tests:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Принудительный запуск симулятора
    - name: Boot simulator
      run: |
        xcrun simctl boot "iPhone 15 Pro"

    # Запуск только снапшот-тестов с новой схемой
    - name: Run Snapshot Tests
      run: |
        xcodebuild test -scheme Separated_snapshots -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -destination-timeout 120 CODE_SIGNING_ALLOWED=NO | xcpretty